{% set name = "ncvis" %}
{% set version = "1.5.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - path: ../

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp     # [osx]
  host:
    - llvm-openmp     # [osx]
    - python
    - setuptools
    - numpy
    - cython >=3,<4
    - pybind11 >=2,<3
  run:
    - llvm-openmp     # [osx]
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.10,<2
test:
  files:
    - test.py
    - test_init.py
  requires:
    - pytest
    - numpy
    - ncvis
  commands:
    - python test_init.py
    - pytest -v test.py


about:
  home: https://github.com/stat-ml/ncvis
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: NCVis is an efficient solution for data visualization
  description: |
    NCVis is an efficient solution for data visualization. It uses HNSW <https://github.com/nmslib/hnswlib> for fast nearest neighbors graph construction and a parallelised noise contrastive estimation for building the graph embedding.
  dev_url: https://github.com/stat-ml/ncvis
