trigger:
- master

pr:
- master

extends:
  template: azure_templates/all.yml
  parameters:
    pythonVersions:
    - '3_8'
    - '3_9'
    - '3_10'
    platforms:
    - 'linux'
    - 'macos'
    - 'windows'
