parameters:
  - name: pythonVersions
    type: object
    default: []

jobs:
- job:
  strategy:
    matrix:
      ${{ each pythonVersion in parameters.pythonVersions }}:
        macOS Python ${{ pythonVersion }}:
          imageName: 'macOS-latest'
          # To be consistent with conda-forge approach
          # https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
          # Don't forget to update the option in the conda_build_config.yaml
          target_platform: 10.9
          # Hack around 3.10 being called 3_10 in the matrix
          python.version: ${{ replace(pythonVersion,'_','.') }}

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: true

  - bash: |
      wget https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX$(target_platform).sdk.tar.xz
      tar xf MacOSX$(target_platform).sdk.tar.xz -C /opt
    displayName: Install MacOSX $(target_platform) SDK

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - bash: | 
      conda config --set always_yes yes --set anaconda_upload no
      conda update -q conda
      conda create -n test python=$(python.version) conda-build conda-verify
    displayName: Create environment

  - bash: |
      source activate test
      conda build --no-test .
      CONDA_PKG=$(conda-build --output .)
      echo "##vso[task.setvariable variable=CONDA_PKG]$CONDA_PKG"
    displayName: Build
  
  - bash: |
      source activate test
      conda build -t $CONDA_PKG
    displayName: Test

  - script: |
      source activate test
      conda install anaconda-client
      anaconda -t $(Conda Token) upload --force $CONDA_PKG
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')  
    displayName: Upload to Anaconda
