parameters:
  - name: pythonVersions
    type: object
    default: []

jobs:
- job:
  strategy:
    matrix:
      ${{ each pythonVersion in parameters.pythonVersions }}:
        Windows Python ${{ pythonVersion }}:
          imageName: 'windows-latest'
          python.version: ${{ pythonVersion }}

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    submodules: true

  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  # Windows Driver Frameworks is also located in that directory and is detected as SDK...
  - script: |
      rename "C:\Program Files (x86)\Windows Kits\10\include\wdf" "10.0"      
    displayName: Fix SDK names

  - script: | 
      call conda config --set always_yes yes --set anaconda_upload no
      call conda update -q conda
      call conda create -n test python=$(python.version) conda-build conda-verify
    displayName: Create environment

  - script: |
      call activate test
      for /f %%i in ('conda build . --output') do set CONDA_PKG=%%i
      echo "##vso[task.setvariable variable=CONDA_PKG]%CONDA_PKG%"
      call conda-build --no-test .
    displayName: Build
  
  - script: |
      call activate test
      call conda-build -t %CONDA_PKG%
    displayName: Test

  - script: |
      call activate test
      call conda install anaconda-client
      call anaconda -t $(Conda Token) upload --force %CONDA_PKG%
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')  
    displayName: Upload to Anaconda